apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cse-undergrad-gp-manage-prod
resources:
- namespace.yaml
- secret.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
images:
- name: scgskku/cse-undergrad-gp-manage
  newTag: 0bc366c36551466f0142505534d4c048c91b387f
