apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cse-undergrad-gp-manage-prod
resources:
- namespace.yaml
- secret.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
images:
- name: scgskku/cse-undergrad-gp-manage
  newTag: ac67a6936e9a6c77e7cc3745545c16cbf96278af
