apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cse-undergrad-gp-manage-prod
resources:
- namespace.yaml
- secret.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
images:
- name: scgskku/cse-undergrad-gp-manage
  newTag: 79b9590589d7e57d5a54295b4a14c013d4911bce
